apiVersion: v1
kind: Secret
metadata:
  name: secret-pod-vol
type: Opaque
stringData:
  username: admin
  password: "12345678"
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: nginx:alpine
    volumeMounts:
    - name: test
      mountPath: "/opt"
      readOnly: true
  volumes:
  - name: test
    secret:
      secretName: secret-pod-vol
      items:
          - key: username
            path: user.txt
          - key: password
            path: pass.txt
