apiVersion: v1
kind: Pod
metadata:
  name: "multi-container"
spec:
  containers:
  - name: cont-1
    image: "python:3.6-alpine"
    command: ['sh','-c','echo cont-1 > index.html && python -m http.server 8081']
  - name: cont-2
    image: "python:3.6-alpine"
    command: ['sh','-c','echo cont-2 > index.html && python -m http.server 8082']
