apiVersion: v1
kind: Pod
metadata:
  name: pod-labels-1
  labels:
    app: front
    env: dev
spec:
  containers:
    - name: cont-1
      image: "nginx:alpine"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-labels-2
  labels:
    app: backend
    env: dev
spec:
  containers:
    - name: cont-1
      image: "nginx:alpine"
