apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-test
  labels:
    app: front
spec:
  selector:
    matchLabels:
      app: front
  replicas: 3
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
---
## ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: svc-firts
  labels:
    app: front
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
## NodePort
apiVersion: v1
kind: Service
metadata:
  name: svc-firts
  labels:
    app: front
spec:
  selector:
    app: front
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80