apiVersion: v1
kind: Namespace
metadata:
  name: it
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
  namespace: it
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: it
  labels:
    svc: http
spec:
  replicas: 3
  selector:
    matchLabels:
      svc: http
  template:
    metadata:
      labels:
        svc: http
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            memory: 500M
            cpu: 500m
          limits:
            memory: 500M
            cpu: 500m