apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-min-max-demo-lr
  namespace: prod
spec:
  limits:
  - max:
      memory: 1Gi
      cpu: 1000m
    min:
      memory: 100Mi
      cpu: 100m
    type: Container
