apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-k8s-hands-on
  labels:
    env: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      env: frontend
  template:
    metadata:
      labels:
        env: frontend
    spec:
      containers:
        - name: frontend-k8s-hands-on
          image: ricardoandre97/frontend-k8s-hands-on:v1
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-k8s-hands-on
  labels:
    env: frontend
spec:
  type: NodePort
  selector:
    env: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
