apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-k8s-hands-on
  labels:
    env: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      env: backend
  template:
    metadata:
      labels:
        env: backend
    spec:
      containers:
        - name: backend-k8s-hands-on
          image: ricardoandre97/backend-k8s-hands-on:v2
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: backend-k8s-hands-on
  labels:
    env: backend
spec:
  selector:
    env: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
